### ISSUE TITLE
It appears that default_fog_configuration no longer works

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/capi-release#6]
## Issue
default_fog_connection: doesn't appear to work in release 234

https://github.com/cloudfoundry/capi-release/blob/9cc12b6a8579078619952acd52ca538114bf5c3f/jobs/cloud_controller_ng/spec#L242

## Context
Though a valid default value exists in the spec in order for my CC to work properly I had to provide fog_connection for each of the blobstore configs

## Steps to Reproduce

1. Deploy CF Release 234 with fog.  Don't specify any config for any of the blobstores (should default to fog right?)
2. Attempt to interact with the blobstore

## Expected result

Interaction works

## Current result

Get an error in the logs similar to this (from an hm9000.start but the trace will be similar enough)

```json
{"timestamp":1460742570.8665578,"message":"exception processing subscription for: 'hm9000.start' '{\"message_id\"=>\"c6bc5978-82cb-4a53-715b-8ab472b63e0c\", \"droplet\"
=>\"5c783707-a3b0-4dbe-919d-57cc70068f6d\", \"version\"=>\"367ffbd2-c0e5-4db3-9a46-3e601c932c23\", \"instance_index\"=>0}' \n#<NoMethodError: undefined method `downcase
' for nil:NilClass>\n /var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_n
g/lib/cloud_controller/blobstore/fog/fog_client.rb:27:in `local?'\n/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284c
f7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/blobstore/url_generator.rb:64:in `droplet_download_url'\n/var/vcap/data/packages/cloud_controller_ng
/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/dea/start_app_message.rb:11:in `initialize
'\n/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_control
ler/dea/client.rb:252:in `new'\n/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_co
ntroller_ng/lib/cloud_controller/dea/client.rb:252:in `start_instance_at_index'\n/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-
f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/dea/client.rb:137:in `block in start_instances'\n/var/vcap/data/packages/cloud_control
ler_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/dea/client.rb:135:in `each'\n/var/vc
ap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/dea/cl
ient.rb:135:in `start_instances'\n/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/dea/hm9000/respondent.rb:69:in `process_hm9000_start'\n/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f.1-f99d5f059a284cf7ac19ff6e00ffb5520513de4d/cloud_controller_ng/lib/cloud_controller/dea/hm9000/respondent.rb:25:in `block in handle_requests'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:88:in `yield'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:88:in `run_handler'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:23:in `block (2 levels) in subscribe'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `call'\n/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'","log_level":"error","source":"cc.runner","data":{},"thread_id":47172617773120,"fiber_id":47172624694260,"process_id":13900,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb","lineno":90,"method":"rescue in run_handler"}
```

## Possible Fix

Remove `default_fog_connection` asking everyone to specify a fog configuration for each blobstore type or fix it.

**Comment by youreddy** [comment]
Hello @youngm, 

The `default_fog_connection` is a property that should have been removed when we made webdav changes. Thank you for calling our attention to this. The above commit removes the mention of the property. 

If you feel that your issue has been resolved, please close the issue.  

Thank you, 
@youreddy & @karafelix 
CF CAPI Team

**Comment by youngm** [comment]
Thanks for clearing that up guys.
